### ISSUE TITLE
Uninitialized Property Access:  $webhookClient_Id

### ISSUE THREAD

**Issue by a21ns1g4ts** [MarJose123/filament-webhook-server#10]
The issue is related to a property access. It appears that you are trying to access the property $webhookClient_Id.

The issue occurs when there is a polling feature enabled in the page. Filament is unable to persist properties in a way that they remain available during polling. I haven't found a solution yet.

![image](https://github.com/MarJose123/filament-webhook-server/assets/11599205/83b805a2-1ca5-47f2-8e7d-848d0b313d6f)

**Comment by MarJose123** [comment]
Thank you for reporting the issue, if you have time to fix the issue I'm happy to accept any PR for fixes.

**Comment by MarJose123** [comment]
This is now resolved by changing the property type of the `$webhookClient_Id` to `public` instead of `protected`.

**Comment by a21ns1g4ts** [comment]
nice work
