### ISSUE TITLE
The plugin is making the panel much slower

### ISSUE THREAD

**Issue by Poseidon281** [MarJose123/filament-webhook-server#29]
The webhook part works, but when i press show logs then there are no logs of the webhooks and the database table filament_webhook_server_histories stays empty

There are no error logs

**Comment by MarJose123** [comment]
> The webhook part works, but when i press show logs then there are no logs of the webhooks and the database table filament_webhook_server_histories stays empty
> 
> There are no error logs

You need to enable it from the config
https://github.com/MarJose123/filament-webhook-server/blob/2.x/config%2Ffilament-webhook-server.php#L17

**Comment by Poseidon281** [comment]
>
> You need to enable it from the config https://github.com/MarJose123/filament-webhook-server/blob/2.x/config%2Ffilament-webhook-server.php#L17

It is on. This is my config:
```php
<?php

use Marjose123\FilamentWebhookServer\Pages\WebhookHistory;
use Marjose123\FilamentWebhookServer\Pages\Webhooks;

return [
    /*
     *  Models that you want to be part of the webhooks options
    */
    'models' => [
        \App\Models\User::class,
        \App\Models\Egg::class,
        \App\Models\Node::class,
        \App\Models\Server::class,
        \App\Models\DatabaseHost::class,
        \App\Models\ApiKey::class,
        \App\Models\Mount::class,
    ],
    'polling' => '10s',
    'webhook' => [
        'keep_history' => true,
    ],
    'pages' => [
        Webhooks::class,
        WebhookHistory::class,
    ],
];

```

**Comment by MarJose123** [comment]
Can you check this for me

1. Check if there are any error logs in your laravel.log file that is related to this
2. Check if migration file is migrated and existed in your DB
3. Check what version is `spatie/laravel-webhook-server` that you have installed currently
4. Check if you got any console error when opening the webhook history page
5. What Laravel Version you are using?

I will investigate this once during my free time.

PR is always welcome 🥂

**Comment by Poseidon281** [comment]
> Can you check this for me
> 
> 1. Check if there are any error logs in your laravel.log file that is related to this
> 2. Check if migration file is migrated and existed in your DB
> 3. Check what version is `spatie/laravel-webhook-server` that you have installed currently
> 4. Check if you got any console error when opening the webhook history page
> 5. What Laravel Version you are using?
> 
> I will investigate this once during my free time.

1. No error logs that are related to this
2. Both tables exist in my DB
3. 3.8.1
4. Everything works fine with the webhook page except that the logs are not showing up
5. laravel/framework = v11.10.0

**Comment by Poseidon281** [comment]
> PR is always welcome 🥂
@MarJose123 

I will make a PR soon with some optimizations. 2 things for now. 

1. Is there a reason why there is no edit option for the webhooks once they are made. There is only a view option

2. Someone noticed that after the installation of the composer packages the panel became much slower. Any idea's on how the plugin can fix this? Perhaps the observer could be adjusted? Any help you can offer with the PR would be greatly appreciated

![image](https://github.com/user-attachments/assets/9c9a7ff6-1d00-4024-8323-05ded014d77f)
![image](https://github.com/user-attachments/assets/03a76e23-dcdb-4022-8345-a80627d48def)



P.S for some reason after i reinstalled the plugin the logs did work so that issue is resolved

**Comment by MarJose123** [comment]
> > PR is always welcome 🥂
> > @MarJose123
> 
> I will make a PR soon with some optimizations. 2 things for now.
> 
> 1. Is there a reason why there is no edit option for the webhooks once they are made. There is only a view option
> 2. Someone noticed that after the installation of the composer packages the panel became much slower. Any idea's on how the plugin can fix this? Perhaps the observer could be adjusted? Any help you can offer with the PR would be greatly appreciated
> 

probably it was caused by the table polling as it was set by default to `'polling' => '10s',` in the config file

**Comment by Poseidon281** [comment]
> probably it was caused by the table polling as it was set by default to `'polling' => '10s',` in the config file

What do you recommend?

**Comment by MarJose123** [comment]
you can find what is the best spot for you, I suggest to have it around 5min-15min so that it will not prevent other network activities.

**Comment by Poseidon281** [comment]
> you can find what is the best spot for you, I suggest to have it around 5min-15min so that it will not prevent other network activities.

Can you reopen the issue?

Because i have tried everything from 5 to 20 min but there are no changes. Even if i just remove getTablePollingInterval the plugin still slows down my panel a lot

**Comment by MarJose123** [comment]
> > you can find what is the best spot for you, I suggest to have it around 5min-15min so that it will not prevent other network activities.
> 
> Can you reopen the issue?
> 
> Because i have tried everything from 5 to 20 min but there are no changes. Even if i just remove getTablePollingInterval the plugin still slows down my panel a lot

can you check your network on how many seconds it takes before it load the datatables?

**Comment by MarJose123** [comment]
You can try to extend the page class and have it customize.
you can try this https://v2.filamentphp.com/tricks/fast-table-pagination method

reference: https://filamentphp.com/docs/3.x/tables/advanced#using-cursor-pagination
