### ISSUE TITLE
Possible bug in model observer registration

### ISSUE THREAD

**Issue by a21ns1g4ts** [MarJose123/filament-webhook-server#34]
https://github.com/MarJose123/filament-webhook-server/blob/27636958a640c4d186e544362f5273ac3cf26e37/src/FilamentWebhookServerServiceProvider.php#L51

I couldn't understand why there's another level of interaction here if the value of configuration is a simple array. Is there a bug?

**Comment by MarJose123** [comment]
Did you encounter an issue related to that?

**Comment by a21ns1g4ts** [comment]
![image](https://github.com/user-attachments/assets/416fa964-da78-43aa-86f2-dd461762b1ed)
Then, why not this ? 
```php 
 foreach ($MODELS as $MODEL) {
        if (class_exists($MODEL)) {
            $MODEL::observe(ModelObserver::class);
        }
    }

**Comment by MarJose123** [comment]
can you send PR? thanks.

**Comment by a21ns1g4ts** [comment]
resolved in [35](https://github.com/MarJose123/filament-webhook-server/pull/35/)
